version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: patient-service-db
    environment:
      POSTGRES_DB: patient_service_db
      POSTGRES_USER: admin_name
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    networks:
      - internal-net

  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    # Expose the external listener port for client connections
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      # Use KRaft for metadata management, no Zookeeper required
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      # Configure listeners based on your provided environment variables
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    networks:
      - internal-net

  patient-service:
    build: ./patient-service
    container_name: patient-service
    depends_on:
      - postgres
    # ports:
    #   - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/patient_service_db
      SPRING_DATASOURCE_USERNAME: admin_name
      SPRING_DATASOURCE_PASSWORD: your_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - internal-net

  billing-service:
    build: ./billing-service
    container_name: billing-service
    depends_on:
      - postgres
    ports:
      - "8081:8081"
      - "9001:9001"
    networks:
      - internal-net

  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    depends_on:
      - kafka
    ports:
      - "4002:4002"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - internal-net

  api-gateway-service:
    build: ./api-gateway
    container_name: api-gateway-service
    depends_on:
      - patient-service
    ports:
      - "4004:4004"
    networks:
      - internal-net

networks:
  internal-net:
    driver: bridge