server:
  port: 4004
spring:
  cloud:
    gateway:
      routes:

        ### REST Client : http://localhost:4004/api/patients
        ### API Gateway : http://patient-service:8080/patients
        ### Patient Service : /patients
        - id: patient-service-route
          uri: http://host.docker.internal:8080
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation
      
        ### REST Client : http://localhost:4004/api-docs/patients
        ### API Gateway : http://patient-service:8080/v3/api-docs
        ### Patient Service : /v3/api-docs
        - id: api-docs-patient-route
          uri: http://host.docker.internal:8080
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients, /v3/api-docs

        - id: auth-service-route
          uri: http://host.docker.internal:4005
          predicates:
           - Path=/auth/**
          filters:
           - StripPrefix=1
        
        - id: api-docs-auth-route
          uri: http://host.docker.internal:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth, /v3/api-docs