### Update Patient Information
PUT http://localhost:8080/patients/{patientId}
Content-Type: application/json

{
  "name": "Bhavya Kapadia",
  "email": "ro45@example.com",
  "address": "Ananta Campus Google BLR",
  "dateOfBirth": "2025-10-04"
}
###
